### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [dajwill/railsApp#1]
I love the look of the site and it's nice to see Materialize in action! :smiley: There are two things I'd like you to update though, detailed below:

### Indentation

The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

### Missing helper method

It looks like the last criterion of the project isn't fulfilled yet:

> have at least 1 helper method that is used for some visible effect on at least 1 page

---

Let me know when both of these are updated and I'll take another look.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by dajwill** [comment]
Yeah, sorry I completed this fix with you and didn't even think to close this. I am using the a geocoder helper on the home page.

**Comment by chrisvfritz** [comment]
Excellent! :+1:
